### ISSUE TITLE
Extended Cogs mod will not load correctly on servers?

### ISSUE THREAD

**Issue by NovaLynxie** [Rabbitminers/Extended-Flywheels#17]
Hi there, I am reporting an issue with the Extended Cogwheels mod addon for Create Fabric.
Am running Fabric for Minecraft 1.19.2

Version information:
Mod version: extendedcogs-1.19.2-0.5.0.g-1.0.0-fabric
Create Fabric: create-fabric-0.5.0g-796+1.19.2
Fabric version: 0.14.13 using fabric-api-0.73.0+1.19.2

The issue/bug:
It seems to load just fine in singleplayer, yet the mod crashes when loaded in a server environment.

Steps to reproduce:
1) Setup a server environment.
2) Install Fabric and Create mods/addons and any dependencies they need.
3) Launch the server and observe the console for the following error:

`[16:59:56] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'extendedcogs'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.13.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.13-launcher.0.11.1.jar:0.11.1]
Caused by: java.lang.NoClassDefFoundError: com/jozufozu/flywheel/core/PartialModel
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsPartials.block(ExtendedCogwheelsPartials.java:25) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsPartials.<clinit>(ExtendedCogwheelsPartials.java:9) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:51) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.ExtendedCogwheels.onInitialize(ExtendedCogwheels.java:35) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.13.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.jozufozu.flywheel.core.PartialModel
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsPartials.block(ExtendedCogwheelsPartials.java:25) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsPartials.<clinit>(ExtendedCogwheelsPartials.java:9) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:51) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.ExtendedCogwheels.onInitialize(ExtendedCogwheels.java:35) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.13.jar:?]
	... 8 more
`

**Comment by Rabbitminers** [comment]
That's odd thanks for notifying me, I believe I might know where the issue is. Assuming everything goes well there should be a patch available in the next few days

**Comment by spencerfrost** [comment]
Also having this issue! Would love to add this to my server

**Comment by teoshibin** [comment]
Probably the same problem here.
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'extendedcogs'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.14.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.14.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/jozufozu/flywheel/core/PartialModel
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsPartials.block(ExtendedCogwheelsPartials.java:25) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsPartials.<clinit>(ExtendedCogwheelsPartials.java:9) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:51) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.ExtendedCogwheels.onInitialize(ExtendedCogwheels.java:35) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.14.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.jozufozu.flywheel.core.PartialModel
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.14.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsPartials.block(ExtendedCogwheelsPartials.java:25) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsPartials.<clinit>(ExtendedCogwheelsPartials.java:9) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.index.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:51) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at com.rabbitminers.extendedcogs.ExtendedCogwheels.onInitialize(ExtendedCogwheels.java:35) ~[extendedcogs-1.19.2-0.5.0.g-1.0.0+1.19.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.14.jar:?]
	... 7 more
```

**Comment by Rabbitminers** [comment]
Patched In latest beta release
