### ISSUE TITLE
1.18.2 Extended cogwheels causes world crash/unloading/completely unloaded chunks

### ISSUE THREAD

**Issue by stonecoldslate** [Rabbitminers/Extended-Flywheels#21]
as the title says, also crashes when hovering over create block glue, crash log added below
--
[21:09:39] [Render thread/ERROR]: Exception caught during firing event: Registry entry not present: createcasing-extendedgears:brass_large_warped_encased_cogwheel
	Index: 17
	Listeners:
		0: HIGHEST
		1: ASM: class com.github.yeetmanlord.somanyenchants.core.util.PlayerAttributeHandler$TooltipUpdate updateTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		2: HIGH
		3: ASM: class dev.architectury.event.forge.EventHandlerImplClient event(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		4: NORMAL
		5: ASM: class nullblade.createelectricalstonks.ToolTip toolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		6: ASM: class shadows.fastbench.ClientHandler tooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		7: ASM: class com.vendoau.maptooltip.MapTooltip onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		8: ASM: class com.tom.createores.client.ClientEventHandler addToItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		9: ASM: class com.mrcrayfish.guns.item.attachment.impl.Attachment addInformationEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		10: ASM: class com.hollingsworth.arsnouveau.client.PlayerEvent onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		11: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@c0e47d8 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		12: ASM: class net.mehvahdjukaar.supplementaries.common.events.ClientEvents onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		13: ASM: class vectorwing.farmersdelight.client.event.TooltipEvents addTooltipToVanillaSoups(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		14: ASM: class vazkii.quark.base.client.handler.RequiredModTooltipHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		15: ASM: class com.railwayteam.railways.events.ClientEvents addToItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		16: ASM: class slimeknights.tconstruct.tools.client.ModifierClientEvents onTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		17: ASM: class com.simibubi.create.events.ClientEvents addToItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		18: ASM: vazkii.quark.content.building.module.CelebratoryLampsModule@2fc0ede onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		19: ASM: class org.cursegame.minecraft.spawners.registry.ModEventsClient renderTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		20: ASM: top.theillusivec4.curios.client.ClientEventHandler@29ed00b2 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		21: ASM: top.theillusivec4.colytra.client.ClientEventHandler@3010a2cd itemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		22: net.minecraftforge.eventbus.EventBus$$Lambda$4451/0x0000000800cb3458@3a566279
		23: LOW
		24: ASM: class com.dkmk100.arsomega.events.ClientEvents onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		25: LOWEST
		26: ASM: class mcp.mobius.waila.WailaClient onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
java.lang.NullPointerException: Registry entry not present: createcasing-extendedgears:brass_large_warped_encased_cogwheel
	at java.base/java.util.Objects.requireNonNull(Objects.java:334)
	at TRANSFORMER/Registrate.MC1._18._2@1.1.3/com.tterrag.registrate.util.entry.RegistryEntry.get(RegistryEntry.java:91)
	at TRANSFORMER/create@0.5.0.i/com.simibubi.create.foundation.data.CreateRegistrate.getSection(CreateRegistrate.java:110)
	at TRANSFORMER/create@0.5.0.i/com.simibubi.create.content.AllSections.ofItem(AllSections.java:55)
	at TRANSFORMER/create@0.5.0.i/com.simibubi.create.content.AllSections.of(AllSections.java:50)
	at TRANSFORMER/create@0.5.0.i/com.simibubi.create.foundation.item.TooltipHelper.buildToolTip(TooltipHelper.java:272)
	at TRANSFORMER/create@0.5.0.i/com.simibubi.create.foundation.item.TooltipHelper.findTooltip(TooltipHelper.java:264)
	at TRANSFORMER/create@0.5.0.i/com.simibubi.create.foundation.item.TooltipHelper.hasTooltip(TooltipHelper.java:247)
	at TRANSFORMER/create@0.5.0.i/com.simibubi.create.events.ClientEvents.addToItemTooltip(ClientEvents.java:258)
	at net.minecraftforge.eventbus.ASMEventHandler_1342_ClientEvents_addToItemTooltip_ItemTooltipEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.2.0/net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:275)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:768)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.Screen.m_96555_(Screen.java:194)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.Screen.m_6057_(Screen.java:171)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_6057_(CreativeModeInventoryScreen.java:671)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_7025_(AbstractContainerScreen.java:173)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_6305_(CreativeModeInventoryScreen.java:636)
	at TRANSFORMER/forge@40.2.0/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:403)
	at TRANSFORMER/forge@40.2.0/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:890)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

**Comment by Rabbitminers** [comment]
This seems to be an issue with create encased. You can report this to them on their github page

https://github.com/iglee42/CreateCasing
