### ISSUE TITLE
Extended Flywheels 1.2.5-1.19.2-0.2.f crashing with Create 0.5.1a

### ISSUE THREAD

**Issue by edukny94** [Rabbitminers/Extended-Flywheels#32]
**Here I leave you the crash report.**

Details:

	Mod File: /C:/Users/educl/curseforge/minecraft/Instances/Twitch/mods/extendedflywheels-1.2.5-1.19.2-0.5.f.jar
	Failure message: Extended Flywheels (extendedflywheels) has failed to load correctly
		java.lang.NoSuchMethodError: 'com.tterrag.registrate.util.nullness.NonNullSupplier com.simibubi.create.foundation.data.CreateRegistrate.lazy(java.lang.String)'
	Mod Version: 1.2.5-1.19.2-0.5.f
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: 'com.tterrag.registrate.util.nullness.NonNullSupplier com.simibubi.create.foundation.data.CreateRegistrate.lazy(java.lang.String)'

Stacktrace:

	at com.rabbitminers.extendedflywheels.ExtendedFlywheels.<clinit>(ExtendedFlywheels.java:31) ~[extendedflywheels-1.2.5-1.19.2-0.5.f.jar%23628!/:1.2.5-1.19.2-0.5.f] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.8.jar%23871!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.8.jar%23870!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

**Comment by SpottyTheTurtle** [comment]
all Create addons will be broken with 0.5.1 for at least a few days

**Comment by edukny94** [comment]
> all Create addons will be broken with 0.5.1 for at least a few days

I know, just wanted to post it in case no one does.

**Comment by falxie** [comment]
Is there a release with this fixed? Just was trying to update my pack and ran into this.

**Comment by edukny94** [comment]
> Is there a release with this fixed? Just was trying to update my pack and ran into this.

Nope, the mod didn't get an update since I post it here. We have to wait.

**Comment by falxie** [comment]
I thought not, it was confusing to see this issue closed as completed when the problem wasn't actually fixed

**Comment by falxie** [comment]
I was trying my hand at updating it and I think the major roadblock is that the Create version of the mod isn't at 0.5.1 yet
